version: "3.8"
services:
  nginx:
    image: "nginx:1.19-alpine"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:rw
    ports:
      - 80:80
    networks:
      backend:
        ipv4_address: 172.21.2.1
  webapp:
    build: webapp
    networks:
      backend:
        ipv4_address: 172.21.2.2
networks:
  backend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.21.2.0/16"
